services:
  # socat:
  #   image: alpine
  #   container_name: socat-spi
  #   command:
  #     [
  #       "sh",
  #       "-c",
  #       "apk add --no-cache socat && socat -d -d PTY,raw,echo=0,link=/spi-mock/spidev0.0 PTY,raw,echo=0",
  #     ]
  #   tty: true
  #   stdin_open: true
  #   volumes:
  #     - spi-mock:/spi-mock
  #   healthcheck:
  #     test: ["CMD", "sh", "-c", "[ -e /spi-mock/spidev0.0 ]"]
  #     interval: 2s
  #     retries: 5
  #     start_period: 5s
  #     timeout: 2s
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # container_name: go-spi-mock
    ports:
      - "3000:3000"
    working_dir: /app
    # depends_on:
    #   socat:
    #     condition: service_healthy
    # devices:
    #   - "/spi-mock/spidev0.0:/dev/spidev0.0"
    # environment:
    #   - SPI_DEVICE=/spi-mock/spidev0.0
    # tty: true
    # stdin_open: true
    volumes:
      - ./backend:/app
      # - spi-mock:/spi-mock
    command: ./script/run
    networks:
      - default
  frontend:
    # enter the frontend folder

    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: ./script/run
    depends_on:
      - backend
    networks:
      - default
# volumes:
#   spi-mock:
networks:
  default:
