#!/bin/bash

cd "$(dirname "$0")/.." || exit 1

# Build the project for raspberry pi
echo "Building the project for raspberry pi"
CGO_ENABLED=1 GOOS=linux GOARCH=arm GOARM=7 go build -o bin/favolotto ./cmd/favolotto
